version: "3.3"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/app/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web: 
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app